Overwrite port number for liveness/readiness probes
RedHatInsights/clowder pull request #266
Opened 2021-03-10 18:10 UTC by kylape

Devs currently have to manually copy the port number from the
environment spec to their liveness/readiness probes in their app spec.
This would automatically update the probes with the correct port number
given an app uses the HTTPGet handler.

2021-03-15 13:16 UTC, psav commented
This needs a little rethinking due to people using nonstandard ports for their checks, ie checks against metrics, should perhaps be gated behind a check for web port presence

2021-03-17 01:13 UTC, kylape commented
Refined this PR.  Please refer to commit message for details.

2021-03-17 10:53 UTC, psav requested changes

2021-03-17 10:53 UTC, psav commented on config/manager/kustomization.yaml
> +  newTag: 95777a1
This needs removing

2021-03-17 10:53 UTC, psav commented on config/manifests/bases/clowder.clusterserviceversion.yaml
> +    operators.operatorframework.io/builder: operator-sdk-v1.0.0
Same as above

2021-03-17 10:53 UTC, psav commented on controllers/cloud.redhat.com/makers/maker.go
> +	if deployment.WebServices.Public.Enabled {
We need an or in here to keep backwards compat with `.Web` until it's gone

2021-04-30 14:17 UTC, closed without merging

2021-04-30 17:52 UTC, jameswnl commented
is this addressed already? do we still keep the port hardcoded in clowder  app template?

2021-05-02 13:35 UTC, bennyturns commented
Yes, this is addressed in a different PR.

2021-05-02 13:36 UTC, bennyturns commented
Actually let me check with pete and kyle, I am not 100% sure now

2021-05-03 14:15 UTC, BlakeHolifield commented
Yeah @jameswnl this code is in master here: https://github.com/RedHatInsights/clowder/blob/master/controllers/cloud.redhat.com/providers/web/impl.go#L50

We currently don't set that value in the ephemeral or stage environments, so it will be default 10000. You can override and test on a local environment if you'd like.