Added role binding
RedHatInsights/clowder pull request #289
Opened 2021-04-07 10:05 UTC by psav

2021-04-08 17:33 UTC, psav commented on docs/contributing/developing.rst
> +        Name:      app.GetDeploymentName(&deployment),
This needs updating

2021-04-12 15:04 UTC, BlakeHolifield commented on controllers/cloud.redhat.com/providers/serviceaccount/impl.go
> +func createServiceAccount(cache *providers.ObjectCache, ident providers.ResourceIdent, pullSecretNames crd.PullSecrets, nn types.NamespacedName, labeler func(v1.Object)) error {
Does this need to be made "public" for IQE to consume? `CreateServiceAccount`

2021-04-12 15:43 UTC, BlakeHolifield approved these changes

2021-04-16 15:40 UTC, kylape requested changes

2021-04-16 15:40 UTC, kylape commented on bundle/tests/scorecard/kuttl/test-k8s-access/01-assert.yaml
> +  - name: test
Please add RoleBindings to the assert file.

2021-04-16 15:40 UTC, kylape commented on controllers/cloud.redhat.com/providers/serviceaccount/default.go
> +		nn := app.GetDeploymentNamespacedName(&dep)
if you put this above line 83, you could use this in the call to Cache.Get

2021-04-16 15:40 UTC, kylape commented on controllers/cloud.redhat.com/providers/serviceaccount/default.go
> +			Namespace: app.GetDeploymentNamespacedName(&dep).Namespace,
use `nn` here?

2021-04-16 16:07 UTC, kylape approved these changes

2021-04-16 17:07 UTC, merged