Default kafka cluster name to env name
RedHatInsights/clowder pull request #340
Opened 2021-05-14 18:16 UTC by kylape

If the kafka cluster name is not specified in the env spec, then name
the cluster the same as the environment.

2021-05-14 20:01 UTC, kylape commented
/retest

2021-05-18 16:27 UTC, bsquizz requested changes
Spotted 1 thing

2021-05-18 16:27 UTC, bsquizz commented on config/manager/kustomization.yaml
> +  newTag: 7af0d5f6
Probably an accidental change -- `git checkout origin/master config/manager/kustomization.yaml`

2021-05-19 06:41 UTC, psav requested changes

2021-05-19 06:41 UTC, psav commented on controllers/cloud.redhat.com/providers/kafka/strimzi.go
> +			Namespace: getKafkaName(s.Env),
I think this is erroneous, we should be getting the Namespace here, not the name no?

2021-05-21 15:35 UTC, psav commented
/retest

2021-05-21 18:14 UTC, merged