Bump release link on README.md
RedHatInsights/clowder pull request #365
Opened 2021-06-11 16:26 UTC by Victoremepunto

2021-06-11 20:48 UTC, bsquizz commented
I think tests failed because you did not sign the commit, or your gpg key is not present in your app-sre users file.

2021-06-11 20:50 UTC, bsquizz approved these changes

2021-06-14 09:41 UTC, psav requested changes

2021-06-14 09:41 UTC, psav commented on README.adoc
> +minikube kubectl -- apply -f https://github.com/RedHatInsights/clowder/releases/download/0.15.0/manifest.yaml --validate=false
```clowder-manifest-0.15.0.yaml``` has now been created

2021-06-14 09:41 UTC, Victoremepunto commented
@bsquizz  thank you man, I pushed my commit, now signed and that looks like worked :)

2021-06-14 09:47 UTC, Victoremepunto commented on README.adoc
> +minikube kubectl -- apply -f https://github.com/RedHatInsights/clowder/releases/download/0.15.0/manifest.yaml --validate=false
fixed

2021-06-14 09:50 UTC, merged