Added API gateway
RedHatInsights/clowder pull request #378
Opened 2021-06-24 17:50 UTC by psav

2021-06-25 07:30 UTC, psav commented
/retest

2021-06-25 07:33 UTC, psav commented
/retest

2021-06-28 13:32 UTC, BlakeHolifield approved these changes
Looks great! Docs and kuttl tests :+1:

2021-06-28 13:45 UTC, psav commented on controllers/cloud.redhat.com/providers/apigateway/provider.go
> +// GetEnd returns the correct end provider.
bad comment - grr - will fix it up later in my sweep

2021-06-30 13:05 UTC, kylape requested changes

2021-06-30 13:05 UTC, kylape commented on apis/cloud.redhat.com/v1alpha1/clowdenvironment_types.go
> +	Mode ApiGatewayMode `json:"mode,omitempty"`
let's use web provider mode

2021-06-30 13:05 UTC, kylape commented on apis/cloud.redhat.com/v1alpha1/clowdapp_types.go
> +	ApiEndpoint string `json:"apiEndpoint,omitempty"`
nah.  also rename to `ApiPrefix`

2021-07-29 14:00 UTC, closed without merging