Update developer guide location
RedHatInsights/clowder pull request #577
Opened 2022-03-16 18:54 UTC by skarekrow

2022-03-16 18:56 UTC, skarekrow commented
Failure doesn't look related, not sure how it ever could be 😂

2022-03-21 07:35 UTC, psav requested changes

2022-03-21 07:35 UTC, psav commented on docs/antora/modules/usage/pages/getting-started.adoc
> +developer environment, https://github.com/RedHatInsights/clowder/blob/master/docs/antora/modules/ROOT/pages/developer-guide.adoc[follow the developer guide].
https://redhatinsights.github.io/clowder/clowder/dev/developer-guide.html - would be a better link :)

2022-03-21 12:12 UTC, psav commented
Also - do you have your user set up in app-interface? If not - you'll need that for a passing PR

2022-03-24 12:10 UTC, merged