[RHCLOUD-18694] Use pre-push to remove excessive files being updated
RedHatInsights/clowder pull request #587
Opened 2022-03-30 15:07 UTC by BlakeHolifield

Since we have lots of errant files being modified locally and pushed up, we should clear those out as part of our pre-push target. These files can't really be git ignored, but they need to be restricted when they update instead of updated by default.

* config/manager/kustomization.yaml
* bundle/metadata/annotations.yaml 
* cloud.redhat.com/version.txt 
* config/manifests/bases/clowder.clusterserviceversion.yaml

Will now be reverted to the master version and not pushed up.

2022-03-31 10:37 UTC, psav commented
Card number please

2022-04-01 21:49 UTC, bsquizz approved these changes
Yes. Awesome. Thank you :D

2022-04-01 21:58 UTC, bsquizz requested changes

2022-04-01 21:58 UTC, bsquizz commented on Makefile
> +	git checkout origin/master -- config/manager/kustomization.yaml \
One suggestion. We probably want to `git fetch origin` before we do this.

2022-04-07 11:05 UTC, merged