[WIP] adding (cron)job watch-controlled list
RedHatInsights/clowder pull request #676
Opened 2022-07-27 10:38 UTC by gburges

2022-07-27 20:18 UTC, psav commented
Need to rebase and run `make pre-push`

2022-07-28 11:32 UTC, gburges commented
> Need to rebase and run `make pre-push`

did it, but the check still fails, tried make build-template and recommit too. Any ideas?

2022-07-28 15:48 UTC, psav commented
`go mod tidy`

2022-07-29 12:02 UTC, psav requested changes
Sorry @gburges a few things here
1) the subscriptions yaml shouldn't be included here in this PR - let's do it in a separate one
2) Where did all the changes to the go.sum come from? try `go mod tidy -compat=1.17`

2022-07-29 12:40 UTC, gburges commented
> Sorry @gburges a few things here
> 
>     1. the subscriptions yaml shouldn't be included here in this PR - let's do it in a separate one
>  removed
>     2. Where did all the changes to the go.sum come from? try `go mod tidy -compat=1.17`
> yeah, might have overupdated my local setup - now it's ok

2022-07-29 13:36 UTC, psav commented on controllers/cloud.redhat.com/clowdapp_controller.go
> +	_ "github.com/RedHatInsights/clowder/controllers/cloud.redhat.com/providers/job"
Remove this line

2022-07-29 18:39 UTC, psav commented
This actually isn't required - we found a different bug which is causing the behaviour you described and this won't fix it :)

2022-07-29 18:39 UTC, closed without merging