[WIP] Clowder jenkinsfile PR Check Enhancement
RedHatInsights/clowder pull request #792
Opened 2023-03-22 20:00 UTC by maknop

2023-03-27 19:23 UTC, BumbleFeng commented
/retest

2023-03-27 19:29 UTC, BumbleFeng commented
/retest

2023-03-27 19:31 UTC, BumbleFeng commented
/retest

2023-03-27 19:36 UTC, BumbleFeng commented
/retest

2023-03-27 21:27 UTC, maknop commented
/retest

2023-03-29 20:19 UTC, maknop commented
/retest

2023-04-07 16:54 UTC, maknop commented
/retest

2023-04-10 15:05 UTC, maknop commented
/retest

2023-11-07 16:28 UTC, maknop commented
/retest

2023-11-07 16:42 UTC, adamrdrew commented
/retest

2023-11-08 13:39 UTC, Victoremepunto requested changes
I'm sorry, I don't think this is in an appropriate state to be merged.

There are several spots where I don't quite understand the intention behind the changes or if the changes are actually an improvement compared to the original script.

I left comments to ask for clarification in all these places, please feel free to schedule some time to review this work together if needed.

2023-11-10 16:53 UTC, Victoremepunto approved these changes
I think it looks good, great job!

2023-11-10 16:53 UTC, Victoremepunto commented on ci/unit_tests.sh
> +curl -s ${HELPER_FUNCTIONS} > .general.sh && source "./.general.sh"
is this still being used ? if it's not please let's remove it.

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +docker rm $tempid
quotes 
```suggestion
docker rm "$tempid"
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +IMG=$IMAGE_NAME:$IMAGE_TAG make docker-push
```suggestion
IMG="${IMAGE_NAME}:${IMAGE_TAG}" BASE_IMG="$BASE_IMG" make docker-build
IMG="${IMAGE_NAME}:${IMAGE_TAG}" make docker-push
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/build_push_base_img.sh
> +    BASE_IMG=$BASE_IMG make docker-build-and-push-base
```suggestion
    BASE_IMG="$BASE_IMG" make docker-build-and-push-base
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +IMG=$IMAGE_NAME:$IMAGE_TAG BASE_IMG=$BASE_IMG make docker-build
```suggestion
IMG="${IMAGE_NAME}:${IMAGE_TAG}" BASE_IMG="$BASE_IMG" make docker-build
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +IMG=$IMAGE_NAME:$IMAGE_TAG make docker-push
```suggestion
IMG="${IMAGE_NAME}:${IMAGE_TAG}" make docker-push
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +docker build -f Dockerfile.test --build-arg BASE_IMAGE=${BASE_IMG} -t $CONTAINER_NAME .
```suggestion
docker build -f Dockerfile.test --build-arg BASE_IMAGE="$BASE_IMG" -t "$CONTAINER_NAME" .
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +    ./ci/minikube_e2e_tests_inner.sh
```suggestion
docker run -i \
    --name "$CONTAINER_NAME" \
    -v "${PWD}:/workspace:ro" \
    -v "$($PWD/bin/setup-envtest use -p path):/bins:ro" \
    -e IMAGE_NAME="$IMAGE_NAME" \
    -e IMAGE_TAG="$IMAGE_TAG" \
    -e QUAY_USER="$QUAY_USER" \
    -e QUAY_TOKEN="$QUAY_TOKEN" \
    -e MINIKUBE_HOST="$MINIKUBE_HOST" \
    -e MINIKUBE_ROOTDIR="$MINIKUBE_ROOTDIR" \
    -e MINIKUBE_USER="$MINIKUBE_USER" \
    -e CLOWDER_VERSION="$CLOWDER_VERSION" \
    "$BASE_IMG" \
    ./ci/minikube_e2e_tests_inner.sh
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/minikube_e2e_tests.sh
> +docker cp $CONTAINER_NAME:/container_workspace/artifacts/ $PWD
```suggestion
docker cp "${CONTAINER_NAME}:/container_workspace/artifacts/" .
```

2023-11-10 16:53 UTC, Victoremepunto commented on ci/build_push_base_img.sh
> +    BASE_IMG=$BASE_IMG make docker-build-and-push-base
```suggestion
    BASE_IMG="$BASE_IMG" make docker-build-and-push-base
```

2023-11-10 20:23 UTC, adamrdrew approved these changes
Let's Get This Merged!

2023-11-10 20:30 UTC, bsquizz approved these changes
LGTM!

2023-11-10 20:32 UTC, adamrdrew approved these changes

2023-11-13 09:57 UTC, Victoremepunto approved these changes
LGTM

2023-11-13 09:58 UTC, merged