Add parallelEnabled and parallelWorkerCount to CJI spec which sets corresponding IQE vars.
RedHatInsights/clowder pull request #802
Opened 2023-04-17 09:47 UTC by san7ket

Adds

2023-04-17 11:14 UTC, san7ket commented
@bsquizz added the two variables from IQE hopefully it works, do we also need updates in bonfire ?

2023-04-17 13:12 UTC, san7ket commented
Any pointers on why the check is failing ?

2023-04-20 18:39 UTC, bsquizz requested changes
This is looking ok so far -- you are just missing one key piece which is to set the env var values onto the pod at this section of code:

https://github.com/RedHatInsights/clowder/blob/master/controllers/cloud.redhat.com/providers/iqe/impl.go#L52

You'll want 2 new entries:
```
{Name: "IQE_PARALLEL_ENABLED", Value: cji.Spec.Testing.Iqe.ParallelEnabled},
{Name: "IQE_PARALLEL_WORKER_COUNT", Value: cji.Spec.Testing.Iqe.ParallelWorkerCount},
```

If empty strings get passed in for these env vars it is fine, the IQE container entrypoint will just use the defaults set in `run.py` in that case.

2023-04-20 18:46 UTC, bsquizz commented
> do we also need updates in bonfire ?

Yes, we would need an update in bonfire as well for the `bonfire process-iqe-cji` and `bonfire deploy-iqe-cji` commands to be able to set these 2 new options.

1. We'd need to update the IQE CJI template here to add the 2 new options:
https://github.com/RedHatInsights/bonfire/blob/master/bonfire/resources/default-iqe-cji.yaml#L23

2. Then add new `click` CLI arguments that allow you to change the values passed to the CJI template if desired:
https://github.com/RedHatInsights/bonfire/blob/6c639bec0716aae0594f0fb51f76c213219200cc/bonfire/bonfire.py#L547

3. Then add the new click args to these 2 functions:
* https://github.com/RedHatInsights/bonfire/blob/6c639bec0716aae0594f0fb51f76c213219200cc/bonfire/bonfire.py#L1272
* https://github.com/RedHatInsights/bonfire/blob/6c639bec0716aae0594f0fb51f76c213219200cc/bonfire/bonfire.py#L1314

4. Finally, you'll notice those 2 functions above call `process_iqe_cji` -- you'd want to pass the new click args on to that function. That is the function that handles running `oc process` on the template: https://github.com/RedHatInsights/bonfire/blob/6c639bec0716aae0594f0fb51f76c213219200cc/bonfire/processor.py#L128

2023-04-27 13:41 UTC, san7ket commented on controllers/cloud.redhat.com/providers/iqe/impl.go
> +		{Name: "IQE_PARALLEL_WORKER_COUNT", Value: cji.Spec.Testing.Iqe.ParallelWorkerCount},
@bsquizz have already added these

2023-04-27 13:42 UTC, san7ket commented
This helps I will work on bonfire changes early next week

2023-04-27 19:43 UTC, bsquizz commented on controllers/cloud.redhat.com/providers/iqe/impl.go
> +		{Name: "IQE_PARALLEL_WORKER_COUNT", Value: cji.Spec.Testing.Iqe.ParallelWorkerCount},
thanks, not sure how I missed this :)

2023-04-27 19:44 UTC, bsquizz approved these changes

2023-04-27 19:46 UTC, adamrdrew commented
Small surface area and kuttl tests Looks good to me!

2023-04-27 19:47 UTC, adamrdrew approved these changes
This all looks good to me!

2023-04-27 19:47 UTC, merged