Adds IQE_RP_ARGS reportportal and IQE_IBUTSU_SOURCE args to CJIs
RedHatInsights/clowder pull request #842
Opened 2023-07-20 19:18 UTC by san7ket

There are two variables those were added to iqecore to integrate with report-portal and also specify ibutsu-source for the test run

2023-07-20 19:20 UTC, san7ket commented
cc @bsquizz

2023-07-25 19:28 UTC, bsquizz requested changes
Looks good, just need to follow the json property naming convention

2023-07-25 19:28 UTC, bsquizz commented on apis/cloud.redhat.com/v1alpha1/clowdjobinvocation_types.go
> +	RpArgs string `json:"RpArgs,omitempty"`
The JSON property name should use `camelCase`

```suggestion
	RpArgs string `json:"rpArgs,omitempty"`
```

2023-07-25 19:28 UTC, bsquizz commented on apis/cloud.redhat.com/v1alpha1/clowdjobinvocation_types.go
> +	IbutsuSource string `json:"IbutsuSource,omitempty"`
Same here

```suggestion
	IbutsuSource string `json:"ibutsuSource,omitempty"`
```

2023-07-25 19:28 UTC, bsquizz commented on config/crd/bases/cloud.redhat.com_clowdjobinvocations.yaml
> +                      IbutsuSource:
When you update the above properties, just make sure to `make pre-push` and the property names here should get updated.

2023-07-25 19:28 UTC, bsquizz commented on config/crd/bases/cloud.redhat.com_clowdjobinvocations.yaml
> +                      RpArgs:
`make pre-push` will probably take care of this

2023-07-25 19:28 UTC, bsquizz commented on tests/kuttl/test-iqe-jobs-selenium/01-pods.yaml
> +      RpArgs: "true"
Update to camelCase here

2023-07-25 19:28 UTC, bsquizz commented on tests/kuttl/test-iqe-jobs-vault/01-pods.yaml
> +      RpArgs: "true"
Here as well

2023-07-25 19:28 UTC, bsquizz commented on tests/kuttl/test-iqe-jobs/01-pods.yaml
> +      RpArgs: "true"
And here :)

2023-07-25 19:28 UTC, bsquizz commented on tests/kuttl/test-iqe-jobs/03-pods-with-view.yaml
> +      RpArgs: "true"
Here as well

2023-08-01 19:23 UTC, bsquizz approved these changes

2023-08-11 15:23 UTC, merged