Fix typo
RedHatInsights/clowder pull request #857
Opened 2023-09-11 15:12 UTC by juandspy

2023-09-11 18:04 UTC, bsquizz requested changes

2023-09-11 18:04 UTC, bsquizz commented on controllers/cloud.redhat.com/version.txt
> +v0.61.0-16-gb20e0094
Need to run `make pre-push` here to avoid changing this file.

2023-09-12 10:27 UTC, juandspy commented
@bsquizz @psav not sure if the changed files are related to this fix :thinking:

2023-09-12 13:32 UTC, bsquizz commented
You're right, the doc changes looked a little larger than you probably intended. Something is probably different on your environment that was causing the docs to be generated with slight formatting differences. I re-generated the API docs.

2023-09-12 13:32 UTC, bsquizz approved these changes

2023-09-12 18:05 UTC, psav approved these changes

2023-09-12 18:07 UTC, merged